databases:
  - name: exercise_DB
    databaseName: exercise_db_crne
    user: exercise
    region: singapore

services: 
  - type: web
    name: exercise
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: exercise_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

